// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuIz6uppTTrpCUKz6kaJL1yk-ubpDz5n0',
    appId: '1:1007516972326:web:a4dd225382aab0be60fde7',
    messagingSenderId: '1007516972326',
    projectId: 'riverpod-bcc13',
    authDomain: 'riverpod-bcc13.firebaseapp.com',
    storageBucket: 'riverpod-bcc13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD48l-jbpTo3tkdt8LZtIg6XfdNmmQg5uw',
    appId: '1:1007516972326:android:8fa2f8f7cd6c5fce60fde7',
    messagingSenderId: '1007516972326',
    projectId: 'riverpod-bcc13',
    storageBucket: 'riverpod-bcc13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBAFI75OQ2EaqWKlhY9tvaaPSP0jQC71o',
    appId: '1:1007516972326:ios:d2a038fec4dae0ad60fde7',
    messagingSenderId: '1007516972326',
    projectId: 'riverpod-bcc13',
    storageBucket: 'riverpod-bcc13.firebasestorage.app',
    iosBundleId: 'com.example.authUsingFirbaseRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBAFI75OQ2EaqWKlhY9tvaaPSP0jQC71o',
    appId: '1:1007516972326:ios:d2a038fec4dae0ad60fde7',
    messagingSenderId: '1007516972326',
    projectId: 'riverpod-bcc13',
    storageBucket: 'riverpod-bcc13.firebasestorage.app',
    iosBundleId: 'com.example.authUsingFirbaseRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuIz6uppTTrpCUKz6kaJL1yk-ubpDz5n0',
    appId: '1:1007516972326:web:c154e5e7a336ba7760fde7',
    messagingSenderId: '1007516972326',
    projectId: 'riverpod-bcc13',
    authDomain: 'riverpod-bcc13.firebaseapp.com',
    storageBucket: 'riverpod-bcc13.firebasestorage.app',
  );
}
